language: node_js
node_js:
  - 10.9.0
env:
  # Use staging DB for tests
  secure: "yL4iHxAgh+1I3xoQfpBE4M/KDW+Et08dqefP2eH9aL/OZWDP5I6R2Zm70oaM6bDQRMpq6mN7+5hDQ/KqH9t7PSS6jkTOgk8sZXpiE19ng3XVbRXxGw6dlVaNBgM/4oy/zXsiK9tuNdG4JpbKMJg/jxbq/QglFjmh8LAQ2d9CQHP/oPQilGwfBLITmqc9pvFRpHFNpu3ZM6YY87nwCPFr8+4BOsqKWSBSu6PE7uGnaZpXZk+oYxlOHUZYJPrfrNU1g2nx3LQw5jpMSI451LtZvTUpCZM/mjAZu3YuO3aKMhXMeTEwUX1Ew8SAdacOLi1//TVcXBwOtCA5LkIKG+5UuQCKqMuh6T0MswHPxJdzDEFwlfdGivzhJhWrulbLM+C1wqwmxsH1KN3tbu0eDnviirp4MIahz9p8iy9NRD9VrkLVJrKm0+o9mdUj7hIV3sKT1qYaUVTvnUA28o1j+SHdcigCA3KI2y9hesoMfrXGkLTfkfVwzJLwKmB5sH0XU9QBLhYpoKFWaCJGjICPjYfKfSuPn7aNXyiAllDRyT+c5qWQojqSFlUQMLr2aQVl9ceNOiGqHuXgM/k0StFmWbhuSSke7o0S5D9sseyXVoROwc4oPz0+aBAGAIx0/X47BjLLDtRXngWP2yY3Pz+Sz0SGfEZT/ZAcHyNuunlNJMG7CQM="
script:
  - "npm run lint"
  - "npm test"
deploy:
  provider: heroku
  api_key:
    secure: b3zfHTZ89Ilg6bbV4iHjs9xrZqTH69jB+0P8tzq05mo2j6iq8eFHZ8Ta2UmvPmWpXCCWuWSr2/hnzHAMZjxk0tHHe5OF7N3z+ZWAQvy+7P75daj0XHroJyzlurHLGQc+8i6gjdvDx85j/HHYx14gh0oIoFkKksQL3h2eVGKvdx35hAa1EC1zRhFzENV9tEegNbb8weKww2EKY39UZMAJ0j5bk+g0Sg9ZLP65dCaxjhgtI6MQBIiw6IS4Ogkt4Wv0asZycOlOaHKESTj1kJg6Wb77zmWQFxpapoqxMez9zjvcYQsU0y2/llgPx5ibGkfCjdJvFzxAL+2gEOACnBRsvTxco6G+R+PuPL36n7olue5USfUwRSL4229uU3VaNxCkaAuzw9pFq8KUy80D0Rtt+rGrgvU1mEHFiQSr57KDX578qrHRrV9IFXJoOgmyBQdGH3V+OgGo+j0uTYwrKKXu3hlfXlQwRYgVvb0+3sxa8ffT3vPw/hHuuMegWWRrlJTB+I3NftE/hruwxT7e2QrIIQazvaCJ143biCT9jNiZLo7wClz+OCxnVV0mtJgwiEaPJxer3zX+ttiDx1CR2g8+Ijx7GXxfFcpwE3haqT8iRLJJzU5HYjbwTBZU4uBQw2XVr68qdFWqZtKik1ow3OPB2oofrBzBdp29umMxfkRZ+1o=
  app: pf-itba-spi
  on:
    repo: PF-ITBA-SPI/SPI-api
